services:
  api-gateway:
    image: nginx:alpine
    volumes:
      - ./api-gateway:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: unless-stopped

  short-url-service:
    image: short-url-service
    env_file: project-env.sh
    build:
      context: short-url-service
    depends_on:
      - mysql-db

  qr-generate-service:
    image: qr-generate-service
    env_file: project-env.sh
    build:
      context: qr-generate-service

  short-url-log-service:
    image: short-url-log-service
    env_file: project-env.sh
    build:
      context: short-url-log-service
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql/mysql-server
    env_file: project-env.sh
    volumes:
      - ./short-url-database/scripts:/docker-entrypoint-initdb.d
      # - mysql_data:/var/lib/mysql
    # restart: unless-stopped
# volumes:
#   mysql_data: